# Minimal AgentCore Configuration for Local Guide AI
default_agent: "local_guide_ai"

agents:
  local_guide_ai:
    name: "Local Guide AI"
    entrypoint: "agentcore_main:app"
    model:
      provider: "bedrock"
      model_id: "us.amazon.nova-premier-v1:0"
      region: "us-east-1"
      parameters:
        temperature: 0.1
        max_tokens: 2048
    memory:
      mode: "NO_MEMORY"
    environment:
      AWS_REGION: "us-east-1"
      DEBUG_MODE: "false"